sudo: requried
services:
  - docker

before_install:
  - docker build -t charowan/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true charowan/react-test npm run test

after_success:
  - docker build -t charowan/multi-client ./client
  - docker build -t charowan/multi-nginx ./nginx
  - docker build -t charowan/multi-server ./server
  - docker build -t charowan/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push charowan/multi-client
  - docker push charowan/multi-nginx
  - docker push charowan/multi-server
  - docker push charowan/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-eu-north-1-927662313617"
  bucket_path: "docker-multi"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"